import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
        <head>
          <title>Msync - Music by you</title>
            <link rel="icon" type="image/png" href="/public/favicon-96x96.png?v=001"
                  sizes="96x96"/>
            <link rel="icon" type="image/svg+xml" href="/public/favicon.svg?v=001"/>
            <link rel="shortcut icon" href="/public/favicon.ico?v=001"/>
            <link rel="apple-touch-icon" sizes="180x180"
                  href="/public/apple-touch-icon.png?v=001"/>
            <meta name="apple-mobile-web-app-title" content="Msync"/>
            <link rel="manifest" href="/public/site.webmanifest?v=001"/>
        </head>
        <body className="min-h-full flex flex-col">{children}</body>
        </html>
    );
}
